# Generated by Django 3.2.3 on 2021-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_categories', '0001_initial'),
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_categories.ProductsCategories'),
        ),
    ]
