# Generated by Django 3.2.3 on 2021-06-01 13:08

from django.db import migrations, models
import django.db.models.deletion
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_products_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to=eshop_products.models.upload_galleries_image_path)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.products')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'ordering': ('id',),
            },
        ),
    ]
