# Generated by Django 3.2.3 on 2021-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_productsgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_visit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
