# Generated by Django 3.2.3 on 2021-06-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='tittle',
        ),
    ]
