# Generated by Django 3.2.3 on 2021-05-30 14:26

from django.db import migrations, models
import eshop_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0002_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[eshop_account.models.EmailChecker()], verbose_name='email address'),
        ),
    ]
