# Generated by Django 3.2.3 on 2021-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('fax', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('about_us', models.TextField(verbose_name='about us')),
                ('copy_right', models.CharField(max_length=150, verbose_name='copy right')),
                ('address', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
                'ordering': ('-id',),
            },
        ),
    ]
