# Generated by Django 3.2.3 on 2021-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
