# Generated by Django 3.2.3 on 2021-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_alter_settings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
