# Generated by Django 3.2.3 on 2021-06-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esho_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliders',
            options={'ordering': ('id',), 'verbose_name': 'slider', 'verbose_name_plural': 'sliders'},
        ),
    ]
