# Generated by Django 3.2.3 on 2021-06-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-id',), 'verbose_name': 'conatc-us message', 'verbose_name_plural': 'Contact-us messages'},
        ),
    ]
